### ISSUE TITLE
[1.7.10] Crash when growth shrub

### ISSUE THREAD

**Issue by KorDum** [ForestryMC/Binnie#166]
```
java.lang.NullPointerException: Ticking memory connection
	at binnie.extratrees.worldgen.BlockTypeLog.setBlock(BlockTypeLog.java:17)
	at binnie.extratrees.worldgen.WorldGenTree.addBlock(WorldGenTree.java:156)
	at binnie.extratrees.worldgen.WorldGenTree.addWood(WorldGenTree.java:161)
	at binnie.extratrees.worldgen.WorldGenTree.generateTreeTrunk(WorldGenTree.java:121)
	at binnie.extratrees.worldgen.WorldGenTree.generateTreeTrunk(WorldGenTree.java:113)
	at binnie.extratrees.worldgen.WorldGenDefault.generate(WorldGenDefault.java:13)
	at binnie.extratrees.worldgen.WorldGenTree.generate(WorldGenTree.java:108)
	at binnie.extratrees.worldgen.WorldGenTree.generate(WorldGenTree.java:87)
        ...
```

**Comment by KorDum** [comment]
Because
```
java.lang.NoSuchMethodException: binnie.extratrees.worldgen.WorldGenShrub.<init>(forestry.api.world.ITreeGenData)
```

**Comment by KorDum** [comment]
The problem is not only in the shrubs.
