### ISSUE TITLE
[1.7.10] Error Wrong primary allele for {flower} Should be: IAlleleTreeSpecies

### ISSUE THREAD

**Issue by KorDum** [ForestryMC/Binnie#222]
```
[16:24:06 FATAL]: Wrong primary allele for: {DELPHINIUM, DELPHINIUM}. Should be: IAlleleTreeSpecies
[16:24:06 ERROR]: An Entity Forestry.butterflyGE(forestry.lepidopterology.entities.EntityButterfly) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
net.minecraft.util.ReportedException: Loading entity NBT
        at net.minecraft.entity.Entity.func_70020_e(Entity.java:1754) ~[sa.class:?]
        at net.minecraft.entity.EntityList.func_75615_a(EntityList.java:173) [sg.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:487) [aqk.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:44) [ChunkIOProvider.class:1.7.10-1614.58]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15) [ChunkIOProvider.class:1.7.10-1614.58]
        at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189) [AsynchronousExecutor$Task.class:1.7.10-1614.58]
        at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354) [AsynchronousExecutor.class:1.7.10-1614.58]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30) [ChunkIOExecutor.class:1.7.10-1614.58]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:917) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.RuntimeException: Found Chromosome with invalid Alleles.
NBTTagCompound: [0:{UID1:"botany.flowers.species.delphinium",UID0:"botany.flowers.species.delphinium",Slot:0b,},1:{UID1:"botany.colorDarkSlateBlue",UID0:"botany.colorDarkSlateBlue",Slot:1b,},2:{UID1:"botany.colorDarkSlateBlue",UID0:"botany.colorDarkSlateBlue",Slot:2b,},3:{UID1:"forestry.fertilityLow",UID0:"forestry.fertilityLow",Slot:3b,},4:{UID1:"forestry.territoryAverage",UID0:"forestry.territoryAverage",Slot:4b,},5:{UID1:"binnie.flowerEffectNone",UID0:"binnie.flowerEffectNone",Slot:5b,},6:{UID1:"forestry.lifespanLonger",UID0:"forestry.lifespanLonger",Slot:6b,},7:{UID1:"forestry.toleranceBoth1",UID0:"forestry.toleranceBoth1",Slot:7b,},8:{UID1:"forestry.toleranceNone",UID0:"forestry.toleranceNone",Slot:8b,},9:{UID1:"forestry.toleranceNone",UID0:"forestry.toleranceNone",Slot:9b,},10:{UID1:"forestry.sappinessLow",UID0:"forestry.sappinessLow",Slot:10b,},11:{UID1:"botany.colorSeaGreen",UID0:"botany.colorSeaGreen",Slot:11b,},]
See config option "genetics.clear.invalid.chromosomes".
Missing: {UID1:"botany.flowers.species.delphinium",UID0:"botany.flowers.species.delphinium",Slot:0b,}
        at forestry.core.genetics.Genome.getChromosomes(Genome.java:202) ~[Genome.class:?]
        at forestry.core.genetics.Genome.readFromNBT(Genome.java:234) ~[Genome.class:?]
        at forestry.core.genetics.Genome.<init>(Genome.java:48) ~[Genome.class:?]
        at forestry.arboriculture.genetics.TreeGenome.<init>(TreeGenome.java:44) ~[TreeGenome.class:?]
        at forestry.arboriculture.genetics.Tree.readFromNBT(Tree.java:81) ~[Tree.class:?]
        at forestry.arboriculture.genetics.Tree.<init>(Tree.java:67) ~[Tree.class:?]
        at forestry.arboriculture.genetics.TreeHelper.getMember(TreeHelper.java:156) ~[TreeHelper.class:?]
        at forestry.lepidopterology.entities.EntityButterfly.func_70037_a(EntityButterfly.java:151) ~[EntityButterfly.class:?]
        at net.minecraft.entity.Entity.func_70020_e(Entity.java:1672) ~[sa.class:?]
        ... 12 more
```

Not crash, only output in console. Is this Forestry bug?

**Comment by mezz** [comment]
This is Forestry checking the chromosome and outputting an error log.
It looks like a butterfly was holding pollen from a flower, but Forestry expected the pollen to be from a tree.

**Comment by KorDum** [comment]
That is, we can not do anything about this?

**Comment by mezz** [comment]
This is a bug in 1.7.10 Forestry, it assumes the root is Tree. This is fixed in the latest Forestry by this commit here:
https://github.com/ForestryMC/ForestryMC/commit/1bdbb7e9f8e2c17b81d20a7374576721d7cc14af#diff-093a765e8de3f23cc5175751d8c54f8f

Feel free to backport the fix.
