### ISSUE TITLE
crash binnie-mods-1.12.2-2.5.0.121

### ISSUE THREAD

**Issue by walker-dev** [ForestryMC/Binnie#435]
[crash-2018-03-14_08-52-32-server-txt](https://gist.github.com/boosterdev/0dc97fb7868730bc6120444d020463bc)

**Comment by RusTit** [comment]
@mezz it's regression to my pull request #432

**Comment by RusTit** [comment]
@mezz @Nedelosk the best way is revert changes.
Honestly, I suspected that there could be similar problems, I apologize (I'm still inexperienced with Minecraft modding).

**Comment by CDAGaming** [comment]
Same Issue on my End too, rip...

**Comment by P3rf3ctXZer0** [comment]
Crash on Dedicated Server
https://gist.github.com/P3rf3ctXZer0/8062c07b52089b3ef7857f801be24e44

**Comment by ZeekDaGeek** [comment]
Technically this fixed the crash of Genetics but didn't fix extratrees apparently. I imagine the problem may exist on all modules?

```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Binnie's Extra Trees (extratrees)
Caused by: java.lang.NullPointerException
        at binnie.core.util.I18N.localise(I18N.java:48)
        at binnie.core.liquid.FluidType.getDisplayName(FluidType.java:60)
        at binnie.extratrees.alcohol.CocktailLiquid.getDisplayName(CocktailLiquid.java:24)
        at binnie.extratrees.liquid.Cocktail.registerIngredient(Cocktail.java:164)
        at binnie.extratrees.liquid.Cocktail.registerIngredients(Cocktail.java:174)
        at binnie.extratrees.modules.ModuleAlcohol.registerLiquids(ModuleAlcohol.java:183)
        at binnie.extratrees.modules.ModuleAlcohol.preInit(ModuleAlcohol.java:67)
        at binnie.core.modules.ModuleContainer.runPreInit(ModuleContainer.java:61)
        at binnie.core.modules.BlankModuleContainer.preInitModules(BlankModuleContainer.java:22)
        at binnie.core.AbstractMod.preInit(AbstractMod.java:80)
        at binnie.extratrees.ExtraTrees.preInit(ExtraTrees.java:59)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
        at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
        at com.google.common.eventbus.EventBus.post(EventBus.java:217)
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
        at com.google.common.eventbus.EventBus.post(EventBus.java:217)
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
        at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:602)
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by P3rf3ctXZer0** [comment]
Still crashing 10 minutes after launch

This is not fixed. @Nedelosk 
https://gist.github.com/P3rf3ctXZer0/00b915713602a18623179c9a7b6efcf7

**Comment by Nedelosk** [comment]
I am currently working on a fix.
