### ISSUE TITLE
[1.7.10] Hardcoded Buildcraft API dependency

### ISSUE THREAD

**Issue by Ghostlyr** [ForestryMC/Binnie#547]
Game crashes without Buildcraft mod installed after right click on Lab Stand with database in hand.

```
java.lang.NoClassDefFoundError: buildcraft/api/tools/IToolWrench
	at binnie.genetics.machine.ComponentGUIHolder.onRightClick(ComponentGUIHolder.java:94)
	at binnie.core.machines.Machine.onRightClick(Machine.java:140)
	at binnie.core.machines.BlockMachine.func_149727_a(BlockMachine.java:99)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:376)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: buildcraft.api.tools.IToolWrench
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 14 more
```

binnie-mods 2.0.22.7

**Comment by Nedelosk** [comment]
We no longer make changes to the 1.7.10 version of the mod.
