### ISSUE TITLE
ExtraBees causing server crash. 

### ISSUE THREAD

**Issue by Hunterbradley1** [ForestryMC/Binnie#641]
When loading new chunks in FTB Rev. I keep getting this crashlog on my server. Looks to be something with worldgen?

Description: Exception in server tick loop

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Unknown Source)
	at binnie.extrabees.worldgen.WorldGenHiveMarble.getPosForHive(WorldGenHiveMarble.java:39)
	at forestry.apiculture.worldgen.Hive.getPosForHive(Hive.java:84)
	at forestry.apiculture.worldgen.HiveDecorator.tryGenHive(HiveDecorator.java:108)
	at forestry.apiculture.worldgen.HiveDecorator.decorateHives(HiveDecorator.java:77)
	at forestry.apiculture.ModuleApiculture.decorateBiome(ModuleApiculture.java:965)
	at forestry.modules.InternalModuleHandler.decorateBiome(InternalModuleHandler.java:192)
	at forestry.core.worldgen.WorldGenerator.decorateBiome(WorldGenerator.java:61)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1964_WorldGenerator_decorateBiome_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.world.biome.BiomeDecorator.func_150513_a(BiomeDecorator.java:366)
	at net.minecraft.world.biome.BiomeDecorator.func_180292_a(BiomeDecorator.java:88)
	at net.minecraft.world.biome.Biome.func_180624_a(Biome.java:225)
	at net.minecraft.world.biome.BiomePlains.func_180624_a(BiomePlains.java:106)
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185931_b(ChunkGeneratorOverworld.java:464)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:990)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:110)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
	at net.minecraft.world.World.func_72964_e(World.java:310)
	at net.minecraft.world.World.func_175726_f(World.java:305)
	at net.minecraft.world.World.func_180495_p(World.java:911)
	at net.minecraft.world.gen.feature.WorldGenMinable.func_180709_b(WorldGenMinable.java:76)
	at mcjty.deepresonance.worldgen.DeepWorldGenerator.addOreSpawn(DeepWorldGenerator.java:135)
	at mcjty.deepresonance.worldgen.DeepWorldGenerator.generateWorld(DeepWorldGenerator.java:43)
	at mcjty.deepresonance.worldgen.WorldTickHandler.tickEnd(WorldTickHandler.java:43)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1295_WorldTickHandler_tickEnd_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:274)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:776)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:

**Comment by nstearns96** [comment]
Do you know what version of Binnie's is installed? This looks like an issue we resolved in a recent patch. I would recommend updating to the latest version or contacting the modpack creator and advising them to do the same.
