### ISSUE TITLE
[1.11.2] NPE in TileLeaves.onBlockTick

### ISSUE THREAD

**Issue by marcin212** [ForestryMC/Binnie#92]
```
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
        at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:540)
        at net.minecraft.world.World.func_180501_a(World.java:335)
        at net.minecraft.world.World.func_175656_a(World.java:417)
        at forestry.arboriculture.tiles.TileLeaves.onBlockTick(TileLeaves.java:144)
        at forestry.arboriculture.blocks.BlockForestryLeaves.func_180650_b(BlockForestryLeaves.java:93)
        at net.minecraft.block.Block.func_180645_a(Block.java:494)
        at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:472)
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:219)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by marcin212** [comment]
fixed by https://github.com/ForestryMC/Binnie/commit/7a8dfc3012779d9bb3827dec8dbd566f5b95753c
