### ISSUE TITLE
[1.11.2]  Breeding tracker

### ISSUE THREAD

**Issue by marcin212** [ForestryMC/Binnie#98]
```
net.minecraft.util.ReportedException: Updating screen events
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1708) ~[bes.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056) ~[bes.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372) [bes.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at binnie.core.BinnieCore.handleSpeciesDiscovered(BinnieCore.java:249) ~[BinnieCore.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2_BinnieCore_handleSpeciesDiscovered_SpeciesDiscovered.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
	at forestry.core.genetics.BreedingTracker.registerSpecies(BreedingTracker.java:248) ~[BreedingTracker.class:?]
	at forestry.core.inventory.ItemInventoryAlyzer.analyzeSpecimen(ItemInventoryAlyzer.java:124) ~[ItemInventoryAlyzer.class:?]
	at forestry.core.inventory.ItemInventoryAlyzer.func_70299_a(ItemInventoryAlyzer.java:88) ~[ItemInventoryAlyzer.class:?]
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:70) ~[adl.class:?]
	at forestry.core.gui.slots.SlotForestry.func_75215_d(SlotForestry.java:55) ~[SlotForestry.class:?]
	at net.minecraft.inventory.Container.func_184996_a(Container.java:281) ~[acl.class:?]
	at forestry.core.gui.ContainerForestry.func_184996_a(ContainerForestry.java:81) ~[ContainerForestry.class:?]
	at forestry.core.gui.ContainerItemInventory.func_184996_a(ContainerItemInventory.java:54) ~[ContainerItemInventory.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:551) ~[bnp.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:632) ~[big.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:598) ~[big.class:?]
	at forestry.core.gui.GuiForestry.func_146286_b(GuiForestry.java:152) ~[GuiForestry.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:554) ~[bho.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512) ~[bho.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1695) ~[bes.class:?]
	... 9 more
```

**Comment by marcin212** [comment]
>23:53 	<@mezz>	yes, "Since Forestry 4.2.1: Breeding tracker should be automatically synced, only Forestry should need to call this."
23:53 	<@mezz>	forestry will sync all breeding trackers in IAlleleRegistry#getSpeciesRoot()
23:54 	<@mezz>	hmmm actually
23:54 	<@mezz>	for updates it is done by the breeding tracker
23:54 	<@mezz>	you should probably copy or extend forestry.core.genetics.BreedingTracker

**Comment by Nedelosk** [comment]
The only function of this method was to sync the discovered species with the player. Forestry does this automatically now.

**Comment by marcin212** [comment]
@Nedelosk  Analyzer(genetics module) doesn't add researched data to the Tracker.
